### ISSUE TITLE
关于时空图卷积神经网络中的einsum运算等式

### ISSUE THREAD

**Issue by wuqiangch** [xn1997/TensorRT-EinsumPlugin#1]
你好，在时空图卷积神经网络的操作应该是“nkctv,kvw->nctw”，而你的代码中equation == "nctkv,kvw->nctw"。

**Comment by xn1997** [comment]
你好，确实是这样的，这个仓库主要是提供了一个学习如何写einsum插件的模板，因此这里只实现了这一种简单的操作，你可以仿照着自己实现其他操作，应该不难。

我这里没有实现`nkctv,kvw->nctw`的原因是：
我使用的推理函数是cublasSgemm，这个函数只能进行二维矩阵的运算，而nkctv中的kv并不挨边，所以没办法使用该函数实现这个操作。（如果你可以找到如何实现这种跨维度矩阵运算的库，请告诉我^_^）

所以你可以先将nkctv维度转换为nctkv，然后再使用这个仓库中的算子，这样就可以用这两步替代ST-GCN中的`nkctv,kvw->nctw`操作了，结果应该是一样的。

**Comment by HW140701** [comment]
> 你好，在时空图卷积神经网络的操作应该是“nkctv,kvw->nctw”，而你的代码中equation == "nctkv,kvw->nctw"。

你好，目前即使是最新的TensorRT8依然没有支持einsum算子，而从C++层自己写einsum插件难度比较大，其实我们可以从python层将torch.enisum替换为其他TensorRT支持的常规算子，我将这个想法进行了总结，写在了：[https://www.stubbornhuang.com/1741](https://www.stubbornhuang.com/1741)，我已经使用了这个方法完成了模型转换并且得到正确的推理结果，如果你依然存在这个问题，不妨看下我的想法，吃水不忘挖井人！
