### ISSUE TITLE
Inference Speed 

### ISSUE THREAD

**Issue by vuminhduc97** [xn1997/TensorRT-EinsumPlugin#3]
Hello, thank for customing Einsum layer!
Is Inference Speed good? I used to change this layer by mul & sum, But Inference Speed significantly reduced.

**Comment by xn1997** [comment]
> Hello, thank for customing Einsum layer! Is Inference Speed good? I used to change this layer by mul & sum, But Inference Speed significantly reduced.

I didn't test the speed, just made sure the model could be converted to TensorRT successfully. I think it's OK.

Some people say TensorRT8.2 EA already supports Einsum layer and you can just use it.
https://github.com/xn1997/TensorRT-EinsumPlugin/issues/2#issue-1023296559

**Comment by vuminhduc97** [comment]
I tried this model in 8.2 ver. It's good, but  my some project run on 7.2. I will test the speed. Thank for this source code.
