### ISSUE TITLE
 Cuda Error in findFastestTactic: 700 

### ISSUE THREAD

**Issue by vuminhduc97** [xn1997/TensorRT-EinsumPlugin#4]
Have you met below error? I add Einsum Plugin to TensorRT Lib successfully. But when I convert and serialize onnx--> engine, I met this error:
 [E] [TRT] ../builder/cudnnBuilderUtils.cpp (426) - Cuda Error in findFastestTactic: 700 (an illegal memory access was encountered)
 [E] [TRT] ../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 700 (an illegal memory access was encountered)
terminate called after throwing an instance of 'nvinfer1::CudaError'

**Comment by xn1997** [comment]
> Have you met below error? I add Einsum Plugin to TensorRT Lib successfully. But when I convert and serialize onnx--> engine, I met this error: [E] [TRT] ../builder/cudnnBuilderUtils.cpp (426) - Cuda Error in findFastestTactic: 700 (an illegal memory access was encountered) [E] [TRT] ../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 700 (an illegal memory access was encountered) terminate called after throwing an instance of 'nvinfer1::CudaError'

Sorry, I haven't met this problem. 
You can refer to the following function to determine whether there is a problem with the dimension of input and output.
https://github.com/xn1997/TensorRT-EinsumPlugin/blob/b528d1f0d383bd7e08767de496587a57af6ab4d1/einsum/Einsum.cpp#L146

**Comment by vuminhduc97** [comment]
yep I get it, thank you very much!
